language: node_js
node_js:
  - 'lts/*'
cache: yarn
before_script:
  - yarn build
  - yarn test
script:
  - yarn coverage
  - yarn release
notifications:
  email:
    on_success: never
    on_failure: always
