// flow-typed signature: 261c1d329f3b5a27aaba327b1c4e3d44
// flow-typed version: <<STUB>>/content-type_v^1.0.4/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'content-type'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'content-type' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'content-type/index' {
  declare module.exports: $Exports<'content-type'>;
}
declare module 'content-type/index.js' {
  declare module.exports: $Exports<'content-type'>;
}
