// flow-typed signature: 5e99d0ed26d2d1b8b7f71c06a582f860
// flow-typed version: <<STUB>>/koa-csrf_v^3.0.6/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-csrf'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-csrf' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'koa-csrf/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'koa-csrf/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'koa-csrf/lib/index' {
  declare module.exports: any;
}

declare module 'koa-csrf/test/support/index' {
  declare module.exports: any;
}

declare module 'koa-csrf/test/unit/01-csrf.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'koa-csrf/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'koa-csrf/coverage/lcov-report/prettify'>;
}
declare module 'koa-csrf/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'koa-csrf/coverage/lcov-report/sorter'>;
}
declare module 'koa-csrf/lib/index.js' {
  declare module.exports: $Exports<'koa-csrf/lib/index'>;
}
declare module 'koa-csrf/test/support/index.js' {
  declare module.exports: $Exports<'koa-csrf/test/support/index'>;
}
declare module 'koa-csrf/test/unit/01-csrf.test.js' {
  declare module.exports: $Exports<'koa-csrf/test/unit/01-csrf.test'>;
}
