// flow-typed signature: 20c35e171e1d4254ad3dab5b4b832317
// flow-typed version: <<STUB>>/koa-userauth_v^2.0.1/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-userauth'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-userauth' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'koa-userauth/index' {
  declare module.exports: $Exports<'koa-userauth'>;
}
declare module 'koa-userauth/index.js' {
  declare module.exports: $Exports<'koa-userauth'>;
}
