// flow-typed signature: 6ebdf3f45676660991ff0f156350547d
// flow-typed version: <<STUB>>/koa-joi-router_v^5.1.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-joi-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-joi-router' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'koa-joi-router/joi-router' {
  declare module.exports: any;
}

declare module 'koa-joi-router/output-validation-rule' {
  declare module.exports: any;
}

declare module 'koa-joi-router/output-validator' {
  declare module.exports: any;
}

// Filename aliases
declare module 'koa-joi-router/joi-router.js' {
  declare module.exports: $Exports<'koa-joi-router/joi-router'>;
}
declare module 'koa-joi-router/output-validation-rule.js' {
  declare module.exports: $Exports<'koa-joi-router/output-validation-rule'>;
}
declare module 'koa-joi-router/output-validator.js' {
  declare module.exports: $Exports<'koa-joi-router/output-validator'>;
}
