// flow-typed signature: 5ed93c3efaa4cda5c0c5b6b0906783c1
// flow-typed version: <<STUB>>/koa-ratelimit_v^4.1.2/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-ratelimit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-ratelimit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'koa-ratelimit/index' {
  declare module.exports: $Exports<'koa-ratelimit'>;
}
declare module 'koa-ratelimit/index.js' {
  declare module.exports: $Exports<'koa-ratelimit'>;
}
