// flow-typed signature: db5e0a8e3cb10d7208eebe23bcfb1ec4
// flow-typed version: <<STUB>>/mongoose-bcrypt_vhttps://github.com/GaiAma/mongoose-bcrypt/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mongoose-bcrypt'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mongoose-bcrypt' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mongoose-bcrypt/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mongoose-bcrypt/index' {
  declare module.exports: $Exports<'mongoose-bcrypt'>;
}
declare module 'mongoose-bcrypt/index.js' {
  declare module.exports: $Exports<'mongoose-bcrypt'>;
}
declare module 'mongoose-bcrypt/test/test.js' {
  declare module.exports: $Exports<'mongoose-bcrypt/test/test'>;
}
