// flow-typed signature: d40417572655088a63bb2f7963fbef7a
// flow-typed version: <<STUB>>/openport_v^0.0.5/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'openport'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'openport' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'openport/openport' {
  declare module.exports: any;
}

declare module 'openport/test/openportTest' {
  declare module.exports: any;
}

// Filename aliases
declare module 'openport/openport.js' {
  declare module.exports: $Exports<'openport/openport'>;
}
declare module 'openport/test/openportTest.js' {
  declare module.exports: $Exports<'openport/test/openportTest'>;
}
