// flow-typed signature: 4f1f3d4e1b332ad75a5d72ef30fbf811
// flow-typed version: <<STUB>>/urlencoded-body-parser_v^2.0.1/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'urlencoded-body-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'urlencoded-body-parser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'urlencoded-body-parser/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module 'urlencoded-body-parser/dist.js' {
  declare module.exports: $Exports<'urlencoded-body-parser/dist'>;
}
